# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b54b59a6963b0abc7374cd00b152463df201f05ff4a9c447df9d232a8c2c146dd158160af4401fe67d7e99a0acd85deace6bf56a7df9bd9e2938a558700320c

test:
  secret_key_base: d31ff08ba0a9202b0949d826b824ccc7c3b5fd6192420c71e098d3f4473c5748277417ac7723753e5f3630b3419d388a3a35b1eb213f373fa0440416ff16b6cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
